### ISSUE TITLE
Need to extend item sizes for output

### ISSUE THREAD

**Issue by celiotine** [POSYDON-code/POSYDON-public#208]
When running with the current development branch, I am getting errors that the `ONELINE_MIN_ITEMSIZE` for `event_f` and `mass_transfer_case_f` are not big enough for the output strings in these columns, which is preventing many binaries from being written to the output dataframe. These itemsizes are set on lines 61 & 65 of `binarypopulation.py`. Increasing the size of `event_f` to 25 and `mass_transfer_case_f` to 20 fixes this issue.

**Comment by celiotine** [comment]
Also should extend size of `mass_transfer_case` in `HISTORY_MIN_ITEMSIZ` to 20

**Comment by ka-rocha** [comment]
<img width="1519" alt="Screen Shot 2023-12-11 at 11 52 13 AM" src="https://github.com/POSYDON-code/POSYDON/assets/48293898/2eb45e96-ef25-4845-bc30-fb192a8f469f">

I found a culprit binary, where failing during `step_detached` leaves the binary with an unexpectedly long final event. I suspect the secondary is close to out of the single star grid (?) but did not look further at the error. The orbital period of this systems was ~5600 days. As suggested before, it may be worth having all strings in our output come from a discrete set of names defined in one place for consistency.

**Comment by celiotine** [comment]
Yes @ka-rocha I think the recently added `redirect` events are the strings causing this issue. For example, `redirect_from_CO_HeMS` is 21 characters which is why the previous max length was exceeded. I agree we should discuss renaming things in general and have some procedure to make sure these changes are propagated to the output.

**Comment by maxbriel** [comment]
Since both fail, their last "event" is from the redirect, which doesn't get cleaned in `step_detached`, as mentioned in #218.
A similar thing occurs in `step_SN`, where the state remains `CC1` or `CC2` and the binary fails.

When running a BinaryPopulation, these are caught by a `try/except`, where `binary.event` is rewritten to FAILED.
However, in the `binary.event_history` the last event remains the same as before, ie. `redirect...`,`CC1`, etc.

Even if we fix the writing to file, should we end these binaries like this? Or should we set the state/event of the star/binary to ERR/FAILED?

**Comment by maxbriel** [comment]
The main issue for the shown binary here seems to be that the secondary has a mass outside the grid (with q<0.05), which should be solved in PR #231.

Although it might be worth adding some more informative errors and setting the binary to an FAILED state.

I don't have the period for the double redirect binary shown by @celiotine, but the options are either a period within the `HMS-HMS` grid or outside.

# Period outside the HMS-HMS grid
For outside the grid one gets the following binary, which fails because the secondary is outside the mass grid of single stars.
**A check should be added to the detached step if the masses are within the grids of single stars**, otherwise an appropriate error should be returned. 

S1_mass | S2_mass | orbital_period | state | event | S1_state | S2_state | step_names
-- | -- | -- | -- | -- | -- | -- | --
13.889634 | 0.490231 | 14513.150157 | detached | ZAMS | H-rich_Core_H_burning | H-rich_Core_H_burning | initial_cond
13.889634 | 0.490231 | 14513.150157 | detached | redirect_from_ZAMS | H-rich_Core_H_burning | H-rich_Core_H_burning | step_HMS_HMS
13.889634 | 0.490231 | 14513.150157 | detached | redirect_from_ZAMS | H-rich_Core_H_burning | H-rich_Core_H_burning | step_detached

It FAILS with a ```ValueError: zero-size array to reduction operation maximum which has no identity``` coming from 
`mass_low = np.max(self.grid_mass[M_new > self.grid_mass])`. This is due to the secondary being outside the mass grid. Since the grid parameters are accessible in `step_detached`, should we add the check there before requesting the track data? There is a check for `pd.isna` present now.

# Period inside the HMS-HMS grid


S1_mass | S2_mass | orbital_period | state | event | S1_state | S2_state | step_names
-- | -- | -- | -- | -- | -- | -- | --
13.889634 | 0.490231 | 4513.150157 | detached | ZAMS | H-rich_Core_H_burning | H-rich_Core_H_burning | initial_cond
13.889634 | 0.490231 | 4513.150157 | detached | ZAMS | H-rich_Core_H_burning | H-rich_Core_H_burning | step_HMS_HMS



This returns another error.
```ValueError: The star_1.state = H-rich_Core_H_burning, star_2.state = H-rich_Core_H_burning, binary.event = ZAMS and not H-rich_Core_H_burning - H-rich_Core_H_burning - * - ZAMS```

In `step_HMS_HMS` there is a check for being outside the period range for the HMS-HMS grid, but no separate check for being outside the mass range, as such the final `else` catches this system. Should we try to redirect this system to `step_detached`?  This will then return the error above. Or return a separate error in `step_HMS_HMS`?

**Comment by mkruckow** [comment]
@celiotine could you please check, whether all parts of this issue are solved by PR #239 ? If so, please close the issue.

**Comment by astroJeff** [comment]
This issue is addressed with PR #253. Thank you, @celiotine
