### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by astroJeff** [POSYDON-code/POSYDON-public#247]
Create a "POSYDONError" to be raised rather than e.g., generic "ValueError".

**Comment by celiotine** [comment]
Just encountered a scenario where this would be helpful. I ran two populations of 1 million binaries and both completed fine with no errors thrown in the runtime error files. However, every binary in these populations silently failed due to the typo Max fixed in PR #250. This should never happen in my opinion. If every single binary in the population is failing due to some Python error, the user should know. I am happy to help with this issue.

**Comment by celiotine** [comment]
- [x] add feature to make debugging while running with POSYDON_Exception feasible, print binary initial conditions?
- [x] fix passing error_checking param in .ini file, add to BinaryPopulation_options?, add to defaults.py
- [x] go through code files that are involved in running a binary population and change errors/exceptions to POSYDON errors/exceptions

- [x] Camille: step_MESA, step_SN, step_CEE, binarystar, step_end, binarypopulation, independent_sample, normalized_pop_mass, common_functions, IF_interpolation, interpolation
- [x] Eirini: all DT files, singlestar, simulationproperties, synthetic_population, io, star_formation_history, configfile, constraints
