### ISSUE TITLE
`mt_history_HMS_HMS` unknown for `stable_reverse_MT`

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#284]
In a population run, the `mt_history_HMS_HMS` becomes `unknown` when the `interp_class_HMS_HMS` is `stable_reverse_MT`.

Originally this returned: `"Stable reverse mass-transfer phase"`

The correct output would be `Stable/Unstable reverse mass-transfer phase`.

**Comment by mkruckow** [comment]
Yeah, the issue is, that the new interpolation class is asymmetric: there is now "no_MT", "stable_MT", "unstable_MT", and "stable_reverse_MT", which requires that "stable_MT" and "unstable_MT" can't be treated the same way anymore. I added a case for "stable_reverse_MT", where it was missing (see PR #281 ), nevertheless there would still be the option to get a reverse MT correctly treated in case it has the class `stable_MT` beside `stable_reverse_MT`.

Btw. it should now hopefully give `Stable reverse mass-transfer phase` again, and never `Unstable reverse mass-transfer phase` if the interpolation class is `stable_reverse_MT`, but `Unstable reverse mass-transfer phase` should be able for an interpolation class `unstable_MT` together with MT forward and backward.

**Comment by mkruckow** [comment]
All cases should be solved, please reopen in case there are any issues found again.
