### ISSUE TITLE
I/O issues creating HDF5 files when running pop synth

### ISSUE THREAD

**Issue by celiotine** [POSYDON-code/POSYDON-public#368]
I am getting many of these new errors when running population synthesis on a cluster using job arrays with the current development branch:
<img width="982" alt="Screen Shot 2024-08-02 at 11 07 38 AM" src="https://github.com/user-attachments/assets/61734bd4-ecc2-499f-86fe-07d4ef71ca4b">

Similar errors are happening during the population merging step.

I noticed that now, there are multiple binaries in the final merged HDF5 file that have the same binary index, which is making post-processing and identifying unique binaries very difficult. I have a feeling this could be related to this issue with reading/writing the HDF5 files.

**Comment by mkruckow** [comment]
To me this looks like permission issues. Could you please check, that you have the permissions to write/create the file(s)?

**Comment by celiotine** [comment]
I am running this in my own directory on b1119, so I should have full permissions:
<img width="454" alt="Screen Shot 2024-08-05 at 9 08 14 AM" src="https://github.com/user-attachments/assets/51334451-3cf0-4268-8d06-fbdb5ee2d75a">

**Comment by celiotine** [comment]
Update: with help from @sgossage I think I've found the issue. In my submit scripts, I was manually designating the number of nodes and cores in the population runs (#SBATCH -N 1, #SBATCH -n 40) and this was somehow causing these errors to occur. I am not sure what would have changed from previous versions, where I ran with these settings and everything was fine? But removing these lines from the submit scripts entirely seems to fix the issue.

**Comment by mkruckow** [comment]
According to the slurm documentation, there are several conditions, which can be set separately, but they need to fulfill certain conditions. Those include the options `-N`, `-n`. But usually, this should cause slurm to not launch your jobs instead of causing issues during the job.
The only reason I could imagine, why it causes issues during the run time, would be the request of more resources during runtime than requested in the submission.
But good that you found a solution for you. In the future, you should may be a bit more careful with adding additional request.
