### ISSUE TITLE
Fix `initial_values` in single stellar grids

### ISSUE THREAD

**Issue by ssbvr** [POSYDON-code/POSYDON-public#5]
After PR #4 is merged, re-post process single stellar grids such that initial conditions are read from the MESA history header instead of the first entry of the history, which is after step one of MESA. This accuracy issue is minor, we are talking about deviations of the initial stellar mass of less than 0.02%.

**Comment by astroJeff** [comment]
@ssbvr, was this ever solved?

**Comment by ssbvr** [comment]
I just checked the `grid.initial_values['S1_star_mass']`, which seems to correspond to the sampled initial values. However, all the other columns appearing in the `grid.initial_values` are read from the first entry of the MESA history. Ideally, we would like to have the same behavior of binary grids where in the `grid.initial_values` I believe (please check) we only have the initial conditions (m1, m2, p, met).

**Comment by mkruckow** [comment]
I had a look through the code:

- we always try to get the initial values from the first entry in the history
- if this fails, we try to get the values from the directory name (we use this, because we'd like to get the metallicity value as well, which is not available in the gird point inlist of binary models)
- in the case of initial MT we overwrite the initial values of the masses and period by the one in the grid point inlist (binary girds only)

Currently, we use the first history entry and take other option in case this value is either not available or aimed to be discarded.
**Do we want to follow a different approach? If so, which one?**
There are the three sources:

- first line in history data (may include changes on first MESA step) -> when we require a history (that's currently the case) this will always be available
- directory name (those values are truncated) -> we are limited to precision and possibly by the amount of values at some point, because directory names can't be arbitrary in length, hence we have restrictions given by the file system
- grid point inlist (contains different values depending on grid type, especially single vs. binary) -> we could try to include always all relevant initial parameters here, but we need to do this in the grid creation/running, hence this can only apply to new MESA grids.

**Comment by astroJeff** [comment]
I don't think this is an issue - the star should not significantly evolve in the first timestep, and even if it does, I do not see this as a real problem.
